# Generated by Django 3.1.4 on 2020-12-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contest_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='index',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='problem',
            name='platform',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='prob_id',
            field=models.CharField(max_length=500),
        ),
    ]
