# Generated by Django 3.1.4 on 2020-12-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20201204_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
