# Generated by Django 3.1.4 on 2020-12-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20201204_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('C', 'Challenge')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='editorial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='contest_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='index',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='platform',
            field=models.CharField(choices=[('F', 'Codeforces'), ('C', 'Codechef'), ('S', 'Spoj'), ('U', 'Uva'), ('A', 'Atcoder')], max_length=1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='prob_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
