# Generated by Django 3.1.4 on 2020-12-07 05:12

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20201204_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='platform',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], enum_class=problem.models.platform, max_length=1),
        ),
    ]
