# Generated by Django 3.1.4 on 2020-12-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20201214_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
