# Generated by Django 3.1.4 on 2020-12-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20201214_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('S', 'Super-Hard'), ('C', 'Challenging')], max_length=1, null=True),
        ),
    ]
