# Generated by Django 3.1.4 on 2020-12-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20201215_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='atcoder_contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('startTime', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
