# Generated by Django 3.1.4 on 2020-12-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_atcoder_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcoder_contest',
            name='contestId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='atcoder_contest',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
