# Generated by Django 3.1.4 on 2020-12-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20201216_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='contest_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
