# Generated by Django 3.1.4 on 2020-12-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20201216_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='prob_id',
            field=models.CharField(max_length=50),
        ),
    ]
