# Generated by Django 3.1.4 on 2020-12-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contestId', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('startTime', models.CharField(max_length=50)),
                ('participants', models.CharField(max_length=6)),
                ('Type', models.CharField(choices=[('R', 'Regular'), ('G', 'Gym')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('handle', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=4)),
                ('maxRating', models.CharField(max_length=4)),
                ('rank', models.CharField(max_length=50)),
                ('maxRanking', models.CharField(max_length=50)),
                ('worldRank', models.CharField(blank=True, max_length=6, null=True)),
                ('countryRank', models.CharField(blank=True, max_length=6, null=True)),
                ('organisationRank', models.CharField(blank=True, max_length=6, null=True)),
                ('photoUrl', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeforces.country')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeforces.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='user_contest_rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worldRank', models.CharField(max_length=6)),
                ('countryRank', models.CharField(max_length=6)),
                ('organisationRank', models.CharField(max_length=6)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.user')),
            ],
        ),
        migrations.CreateModel(
            name='organisation_contest_participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.contest')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='country_contest_participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.contest')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.country')),
            ],
        ),
    ]
