# Generated by Django 3.1.4 on 2020-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='maxRanking',
            new_name='maxRank',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
