# Generated by Django 3.1.4 on 2020-12-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0006_auto_20201213_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RenameModel(
            old_name='organisation_contest_participation',
            new_name='organization_contest_participation',
        ),
        migrations.RenameField(
            model_name='organization_contest_participation',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='organisationRank',
            new_name='organizationRank',
        ),
        migrations.RenameField(
            model_name='user_contest_rank',
            old_name='organisationRank',
            new_name='organizationRank',
        ),
    ]
